### ISSUE TITLE
Disable analytics in development

### ISSUE THREAD

**Issue by fabyeah** [okgrow/analytics#133]
I'm getting the `Missing analyticsSettings in Meteor.settings.public` error in development. I didn't provide the Google Analytics settings / tracking code in the development settings.json, because I don't want the development analytics to mix with the production analytics. Is it possible to disable the analytics for development, because I don't like seeing the error in the console...?

**Comment by cfnelson** [comment]
Hey @fabyeah, there is no code in this package that will stop the error from printing. You can see how we check the `analyticsSettings` [here](https://github.com/okgrow/analytics/blob/master/client/constants.js#L4) and [here](https://github.com/okgrow/analytics/blob/master/client/startup.js#L11).

I would suggest though that you create a 2nd GA [property](https://support.google.com/analytics/answer/1042508?hl=en)  and use that one for your dev mode in order to test any analytics you are using. 

Hope this helps. Let me know if you need anything else.

**Comment by fabyeah** [comment]
Ok, thank you, I will do that.
