### ISSUE TITLE
Astronomer.io

### ISSUE THREAD

**Issue by merlinstardust** [okgrow/analytics#135]
Will this package work alongside Astronomer's analytics package?

https://atmospherejs.com/astronomerio/core

**Comment by arrygoo** [comment]
@merlinpatt We haven't tested it against astronomerio, I'm curious to see if they play nice together but there's a good chance they may not work along each other due to this comment on the link you shared: 

`#####NOTE: If you are using the package "percolatestudio:segment.io," you will need to remove this before installing Astronomer. This package sets a global 'analytics' object that makes things a bit, uh, wonky.
`
