### ISSUE TITLE
Google Page Speed

### ISSUE THREAD

**Issue by krishaamer** [okgrow/analytics#165]
Thanks for the amazing plugin!

I'm testing my site with Google Page Speed and it complains because the Google Analytics script is not being cached. Can we cache Analytics so Meteor users could have a nice 100/100 score? :)

```
Leverage browser caching
Setting an expiry date or a maximum age in the HTTP headers for static resources instructs the browser to load previously downloaded resources from local disk rather than over the network.
Leverage browser caching for the following cacheable resources:
https://www.google-analytics.com/analytics.js (2 hours)
```

You can check out the site here: https://www.100objects.fi

**Comment by cfnelson** [comment]
@krishaamer Caching is outside the scope of this package. If you arer looking to improve your page speed you will need to be serving your apps assets, .js and .css from a CDN. This is where you would specify any cache times.

On the note of google analytics, they provide/set the 2 hours cache time because they wish to update the script regularly.
