### ISSUE TITLE
document.title is not updating in properties of page view

### ISSUE THREAD

**Issue by catimos** [okgrow/analytics#167]
Hi
I am using this package with iron router and am updating document.title on every route. 

When I click a new page link on a home page, the new page is tracked correctly with new page's document.title and path.  But when back button is pressed to come back to home page, the home page is tracked with new page's document title and home page's path, url. 

Why is automatic page view logging not picking up the correct document.title for the page ?
I tried setting document.title in OnBeforeaction, OnRun it does not update in properties.

**Comment by cfnelson** [comment]
@catimos How exactly are you setting the `document.title`? 

The behaviour you are experiencing is due to the way you are setting the `document.title` from within iron-router. See this issue here as a starting point https://github.com/iron-meteor/iron-router/issues/292 .

We personally haven't been using `iron-router` for a few years. You can use the 1.0.9 version of this package if you wish to use the routes name instead of dealing with correctly modifying the `document.title`.

Currently we are using this package without the issue you described above in a few of our clients web apps. The apps use [flow-router](https://github.com/kadirahq/flow-router) or [react-router](https://github.com/ReactTraining/react-router) for routing, along with [react-helmet](https://github.com/nfl/react-helmet) to set the `document.title` for each page.

**Comment by catimos** [comment]
It looks like iron router updates document.title of the previous page in history, that is why on pressing back button page view picks up the wrong title.

In case analytics is not sent automatically [autorun = false] , then with iron-router when is the best place  to manually log a page view event ? how do we know page is fully loaded ? onAfteraction may be run multiple times, onRun may not have the relevant data pulled up for showing in title .
any ideas?

**Comment by cfnelson** [comment]
@catimos I haven't used iron-router in over 2 years now, I believe you may find more helpful answer by asking over on iron router's repo. A quick fix is to use v1.0.9 of this package if you are using the routes `name` for analytics. I would recommend using an external package that updates the documents head on dom load. 

However if you are wondering on ways to know when the page is fully loaded you can use [window.onload](https://developer.mozilla.org/en/docs/Web/API/GlobalEventHandlers/onload) however depending on what you actually want you may wish to use the [DOMContentLoaded](https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded). Check the links out as they contain explanations and simple snippets to show you how to use.

It may be worth playing around with the above and inspect what iron router is doing. Will be curious to know if you make any progress. Hope this has been helpful!
