### ISSUE TITLE
error in console with ad blocker

### ISSUE THREAD

**Issue by ipstas** [okgrow/analytics#180]
Is it possible to use a warning instead of the error for ad blocker?
The reason is there are a lot of error tracking services which submit errors in DB. And ad blocker errors are not the errors a developer can fix, so they are useless

**Comment by cfnelson** [comment]
@ipstas Are you referring to a specific error thrown by this package or the errors thrown by `segment` or the `analytics service` you are using?

We currently log `console.error('Missing analyticsSettings in Meteor.settings.public');` otherwise the only other error we log is [here](https://github.com/okgrow/auto-analytics/blob/master/src/index.js#L57).

Most error tracking services provide the ability to filter/ignore certain errors. Will leave this open to see what others think about switching the errors to warnings.

**Comment by ipstas** [comment]
Not sure where it comes from. This is what I got in the console:
`XMLHttpRequest cannot load http://api.mixpanel.com/decide/?verbose=1&version=1&lib=web&token=f77146a5e84dcd3e6aa6dcb474e11ba8&ip=1&_=1496775850324. Redirect from 'http://api.mixpanel.com/decide/?verbose=1&version=1&lib=web&token=f77146a5e84dcd3e6aa6dcb474e11ba8&ip=1&_=1496775850324' has been blocked by CORS policy: Redirect location 'about:blank' has a disallowed scheme for cross-origin requests.`

So if it is not from okgrow, I am sincerely apologizing.

**Comment by cfnelson** [comment]
@ipstas That error message seems to suggest it is a browser policy setting that is causing your problems. Unless this is only occurring with ad-blockers?

I also noticed that mixpanel is coming over `http`. I would recommend that you switch to `https`, you will get warnings or errors for that if your site is served over `https`.

**Comment by ipstas** [comment]
Yes, that was coming with ad-blockers only. If I switch them off, I have no errors
