### ISSUE TITLE
Using GoogleAnalytics via segment.io with disable autorun. Will GA get all data?

### ISSUE THREAD

**Issue by thebarty** [okgrow/analytics#185]
I am using this package and ONLY have segment.io enabled.
I disabled "autorun", as I read in some metric-tutorials, that "tracking less is more". So in Mixpanel I only want the "less"-data, BUT in GoogleAnalytics I want ALL!

QUESTION:
**When only routing thru "segment.io" and `"autorun": false`: Will GoogleAnalytics still be able to give ALL statistics, or is it NOT getting ALL data (as I am only manually sending events via `analytics.page` and `analytics.track`)??**

Any ideas? How do you guys set it up?

**Comment by thebarty** [comment]
By the way: I just noticed that GoogleAnalytics "live preview"mode does NOT work when using the above setup.

Any ideas?

**Comment by RichardLitt** [comment]
Thanks, @thebarty. We'll look into this as soon as we can. 

Regarding your second question: have you tried manually logging a page view, using `analytics.page('page name')`? That's what the README suggests if you have autorun disabled.

**Comment by thebarty** [comment]
Yes, of course: I have manuel page- and track-events placed. Those, plus login events, are displayed in segments debugger

**Comment by cfnelson** [comment]
@thebarty If you disable the `autorun` then you will only receive the events where you are manually calling the `page` or `track` events. By default any`track` or `page` call will send to all the services you have initialised. `autorun` only stops the automatic tracking that we have setup.

If you wish to filter which events go where you have two options:

- Manually set the destinations for each `page` or `track`
```js
// analytics.track(event, [properties], [options], [callback]);
// analytics.page([category], [name], [properties], [options], [callback]);

// Example tracking a Ticket purchase and sending the event only to GA
analytics.track("Bought Ticket", {
  eventName: "Wine Tasting",
  couponValue: 50,
}, {
  integrations: {
    "Mixpanel": false,
    "Google Analytics": true
  }
});
```

- If you are using/paying for segment.io's service you can filter these via their UI interface instead of manually doing the above everywhere.

Check out there docs [here](https://segment.com/docs/sources/website/analytics.js/#selecting-destinations) for more details on the API.

Hope this has been helpful. Happy to answer anything else if I can. 😄
