### ISSUE TITLE
Refused to evaluate a string as JavaScript because 'unsafe-eval'

### ISSUE THREAD

**Issue by alexzaporozhets** [okgrow/analytics#2]
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' http://www.google-analytics.com https://www.google-analytics.com http://cdn.mxpnl.com https://cdn.mxpnl.com".

**Comment by pauldowman** [comment]
I take it you've added the browser-policy package to your app and have set `BrowserPolicy.content.disallowInlineScripts()`, is that right?

I don't think that will work, I think most of the analytics service scripts inject inline scripts. I haven't confirmed this, let me know if that fixes your issue.

**Comment by alexzaporozhets** [comment]
Nope, we did not use browser-policy, .meteor/packages:

```
meteor-platform
insecure
ian:bootstrap-3
ian:accounts-ui-bootstrap-3
accounts-password
accounts-facebook
accounts-google
aldeed:autoform
aldeed:collection2
yogiben:autoform-modals
iron:router
mrt:twit
mrt:moment
meteorhacks:npm
npm-container
meteorhacks:async
autopublish
workman:meteor-editable
pahans:reactive-modal
dburles:collection-helpers
fortawesome:fontawesome
percolate:synced-cron
stevezhu:lodash
reywood:iron-router-ga
meteorhacks:kadira
meteorhacks:zones
```

**Comment by pauldowman** [comment]
Can you check which version of the analytics package you're using? Check `.meteor/versions`. If it's not 0.1.1 can you do `meteor update okgrow:analytics`? There was a previous version that pulled in browser-policy as a dependency rather than a weak dependency, and sometimes Meteor's version solver defaults to the oldest package rather than the newest (although that's only when adding _indirect_ dependencies, so that's actually probably not the issue).

**Comment by pauldowman** [comment]
Can you check which version of the analytics package you're using? Check `.meteor/versions`. If it's not 0.1.1 can you do `meteor update okgrow:analytics`? There was a previous version that pulled in browser-policy as a dependency rather than a weak dependency, and sometimes Meteor's version solver defaults to the oldest package rather than the newest (although that's only when adding *indirect* dependencies, so that's actually probably not the issue).

**Comment by alexzaporozhets** [comment]
Thanks, the problem was solved

**Comment by pauldowman** [comment]
Just curious, was that the solution? It was an old version? I'm not sure how that would happen unless it was a dependency of another package (or unless you actually installed it during the one day window that it had that bug).

**Comment by alexzaporozhets** [comment]
It was an old version
