### ISSUE TITLE
Multiple Google Analytics tags detected [solved]

### ISSUE THREAD

**Issue by safwanolaimat** [okgrow/analytics#202]
Multiple Google Analytics tags detected

**Comment by RichardLitt** [comment]
Thanks @husafwan. It's a bit hard to diagnose this without anymore information. Can you point to an example of how you implemented the code, for instance?

**Comment by cfnelson** [comment]
@husafwan This happens when you have included GA more then once. You most likely have extra analytic scripts added to your websites `<head>`. Check your `html` to locate the script responsible and remove it.

If you provide us with more info, we will be happy to assist further if you need it. 😄 
Closing until then as this issue isn't a bug related to this package.
