### ISSUE TITLE
Package breaks back navigation on Meteor 1.6 if FlowRouter is used

### ISSUE THREAD

**Issue by derwaldgeist** [okgrow/analytics#203]
As described here in detail:

https://github.com/meteor/meteor/issues/9419

after upgrading my app from Meteor 1.5 to 1.6 I faced the problem that the browser back button did not work anymore if the target of the back navigation was the initial page the app had been loaded with.

After hours of search, I could boil this down to a "monkey patched" `history.pushState()` function introduced by `okgrow:analytics`. Once I take this package out, everything works fine. Obviously, this monkey patch worked until Meteor 1.5, but is not compatible with Meteor 1.6 anymore.

**Comment by RichardLitt** [comment]
Thanks for logging and researching this issue, @derwaldgeist! Noted.

**Comment by cfnelson** [comment]
@derwaldgeist Thanks for adding this issue. Could you update the issue title to mention FlowRouter as this bug is specific to FlowRouter. I am also curious to know which versions of this package and flow router you are using. Is their any version changes in these two pkgs when you upgrade to Meteor 1.6. 

Also the code related to this is located over in our [auto-analytics](https://github.com/okgrow/auto-analytics) package. Previously have had other issues relating to flow-router and this integration due to the way it handles [history state](https://github.com/okgrow/auto-analytics/issues/13#issuecomment-336988183).

I also suspect that it's not the [monkey patch](https://github.com/okgrow/auto-analytics/blob/master/src/index.js#L57) but [logPageFirstLoad](https://github.com/okgrow/auto-analytics/blob/master/src/index.js#L35) where we use `window.history.replaceSate` I am guessing this is why `path` disappears from the state object.

**Comment by cfnelson** [comment]
A fix has been created for the above bug and a [PR](https://github.com/okgrow/auto-analytics/pull/19) has been opened on our auto-analytics pkg.

We will publish a new meteor analytics package once `@okgrow/auto-analytics@1.0.6` is released. 

For further details you can read this comment [here](https://github.com/meteor/meteor/issues/9419#issuecomment-347336949).

**Comment by derwaldgeist** [comment]
Thanks again for the very fast fix! Changed the title so it reflects FlowRouter.

**Comment by derwaldgeist** [comment]
Shall I close this issue or do you want to keep it open until the update has been published?

**Comment by cfnelson** [comment]
@derwaldgeist No problems. Lets keep this open until we publish the fix. As I am waiting for a code review on the original PR & will then need to make a new release for meteor analytics once the npm pkg has been published.

**Comment by cfnelson** [comment]
@derwaldgeist `v3.0.5` is published 🎉 . I have tested locally with the Flow Router example and all seems good! 😄 Let me know how the latest release goes for you!

Going to mark this issue as resolved, but please open back up if you have any issues. 👍

**Comment by derwaldgeist** [comment]
Yeah, I can confirm it works after the update. Great work, thanks! 👍
