### ISSUE TITLE
net::ERR_BLOCKED_BY_CLIENT with Ad blocker in production (Mixpanel)

### ISSUE THREAD

**Issue by dylanmcgowan** [okgrow/analytics#205]
My ad blocker (uBlock origin) is preventing Mixpanel from working on one of my sites in production. (www.rayr.co) Is this the intended behavior? It was my understanding that meteor bundles everything together for production, but mixpanel & google analytics are not included in the bundle, they are appended to the `<head>` element instead. The meteor bundle is located in the body now. 

Any idea what's going on?

**Comment by RichardLitt** [comment]
That sounds to me like the expected behaviour for uBlock, which will block mixpanel when it sees it. 

@cfnelson may be able to hep more.

**Comment by cfnelson** [comment]
@dylanmcgowan This is normal behaviour for an Ad-Blocker. Bundling won't stop an Ad Blocker from blocking network requests. They monitor all network requests and block anything related to advertising/analytics etc. This is normally done by checking the domain or the filename even (thats why we give a warning about testing in dev as uBlock origin will read the packages filename and block it). You can see how this happens in Chrome by running the network or perf dev tool on your site.

The Meteor bundle has been located in the `<body>` for quite some time now (since 1.3). Here is the [PR](https://github.com/meteor/meteor/pull/6375) if you are curious.

Hope this has helped. 😄 Let us know if you have any other questions.
