### ISSUE TITLE
Add support for configuration with environment variables  

### ISSUE THREAD

**Issue by alexzaporozhets** [okgrow/analytics#3]
Just a proposal:

```
ANALYTICS_ MIXPANEL_TOKEN="..."
ANALYTICS_ GA_KEY="..."
```

**Comment by pauldowman** [comment]
I don't think that would work, environment variables aren't available on the client, so I'm going to close this.

But if there was any change to how configuration worked I'd rather see it be possible directly in JS. Something like: `Analytics.configure({mixpanel: "...", google: "..."});` The reason is that the config for analytics services aren't sensitive and it's arguably not worth the effort of setting per-environment settings, so there's usually not a really good reason not to just hard-code it in the app. But not a big deal, I'd wait for someone to ask before doing that.

**Comment by jay-depot** [comment]
If you ever consider revisiting this issue, there's a package https://atmospherejs.com/mrt/allow-env which will let you select server-side environment variables to expose to the client side now, which would make this quite doable.

**Comment by KristerV** [comment]
note to self: you can actually use environment variables by using the [METEOR_SETTINGS](https://docs.meteor.com/api/core.html#Meteor-settings) keyword.
