### ISSUE TITLE
Any way to exclude routes?

### ISSUE THREAD

**Issue by ffxsam** [okgrow/analytics#40]
Let's say I wanted to exclude the route `/admin/*` - is that possible? If so, how?

**Comment by tsemana** [comment]
Hi @ffxsam - there's currently no ability exclude routes since we don't see a usecase where you would need to actively avoid tracking specific routes. In our usage, we collect all data through for analytics and use funnels and the tools to focus on the relevant data points. 

Closing this ticket for now, but would be happy to review a PR.

**Comment by ffxsam** [comment]
Well, one use case would be to not track the admin pages of a website.
