### ISSUE TITLE
Add option to disable page views for certain routes

### ISSUE THREAD

**Issue by elie222** [okgrow/analytics#42]
I use some redirects in certain situations and I don't want these to come up as two page views. Another situation where you might not want to count page views is admin pages.

**Comment by benstr** [comment]
Interesting I can see how this could be useful but it looks like the discussion already happened on the analytics.js repo. https://github.com/segmentio/analytics.js/pull/353

But since we control automatically calling `analytics.page()` then we should add something allowing the page function to be disabled... let me whip something up...

**Comment by benstr** [comment]
oops, just realized that link is from the wrong repo... diving more into this now.
