### ISSUE TITLE
FlowRouter doesn't track first pageview

### ISSUE THREAD

**Issue by pyankoff** [okgrow/analytics#58]
Seems like router calls `analytics.page(page.name, page);` before initializing analytics. Is it ok to fix it with timeout?

``````
Meteor.setTimeout(function(){
      analytics.page(page.name, page);
    }, 500);```
``````

**Comment by yim1990** [comment]
+1

**Comment by pauldowman** [comment]
Thanks, we'll take a look as soon as we can.

**Comment by jkatz50** [comment]
+1

**Comment by benstr** [comment]
So we have a race going on. Right now FlowRouter initializes and runs the first route before Analytics initializes. Luckily FlowRouter provides `FlowRouter.wait()` and `FlowRouter.initialize()`. I started playing around with this and should have a solution soon.

**Comment by benstr** [comment]
#69 fixed this issue. look forward to a new app on atmosphere soon.

**Comment by pauldowman** [comment]
Version 1.0.1 released.

**Comment by carinakoo** [comment]
Hi guys. FYI this issue was still happening for me, but the culprit seems to be FlowRouter running the first route before the analytics enter trigger is defined. Using `FlowRouter.wait()` and `FlowRouter.initialize()` in meteor-analytics.js fixed it for me.

Repro steps:
1. Install Meteor Todos example app with okgrow:analytics

```
> git clone https://github.com/meteor/todos
> cd todos
> npm install
> meteor add okgrow:analytics
> echo '{"public": {"analyticsSettings": {"Google Analytics" : {"trackingId": ""}}}}' > settings.json
> meteor --settings settings.json
```
1. In the browser console, turn on debug.
   `> analytics.debug()`
2. Refresh the page. 
   See:
   `analytics:integration:google-analytics initialize`
   Missing:
   `analytics:integration:google-analytics page`
   Note: The todos app has a redirect on the root url, so it actually runs two routes, "App.home" and "Lists.show", and so we should see page tracks for both. In my tests the second route gets tracked when loading from cache, but not when refreshing, and the first route is never tracked.

Thanks!
