### ISSUE TITLE
problem with Amplitude integration in Segment

### ISSUE THREAD

**Issue by neywen** [okgrow/analytics#64]
I have included okgrow:analytics in my meteor project. Using the right Segment.io appKey, I can see all the tracked events in the Segment debugger in real time. great.

Amplitude integration is enabled in the Segment dashboard.
But I can not see any events reported in Amplitude. It keeps saying "no data".

If I deactivate the okgrow:analytics package, and include the Segment javascript initialization code manually, everything's ok : the events are properly transmitted to Amplitude.

I'll keep this working solution for now, but if anyone has an idea, I'm interested.
Thanks.

**Comment by pauldowman** [comment]
Honestly I don't think we'll get to this because we just don't have time to test and fix every possible integration. If you find the issue I'd love a PR. 

But I'm thinking it might be due to analytics.js needing an update perhaps? See also #59 where we want to remove all but the most common integrations, which would also cause us to update to the latest analytics.js right now. Do you want to take a stab at a PR for that? :smiley:

**Comment by neywen** [comment]
Thank you for your message.

I've send the PR, which simply includes the last version of the lib analytics.js (2.11.1 against 2.5.2 if I remember correctly). 
It writes an additional "page" field in each event data context, and that seems to be the issue to get the Amplitude integration work properly.

**Comment by benstr** [comment]
Closed #65

**Comment by pauldowman** [comment]
Version 1.0.1 released. @neywen let me know if that doesn't work for you!
